return {
  ensure_installed = {
    "bash",
    "powershell",
    "csv",
    "dockerfile",
    "markdown",
    "markdown_inline",
    -- "editorconfig",
    -- "gitignore",
    -- "gitattributes",
    -- "jq",
    -- "json",
    -- "jsonc",
    -- "make",
    -- "nix",
    -- "hurl",
    -- "printf",
    -- "requirements",
    -- "terraform",
    -- "yaml",
    -- "toml",
    -- "html",
    -- "css",
    -- "scss",
    -- "javascript",
    -- "typescript",
    -- "python",
    -- "lua",
    -- "luadoc",
    -- "groovy",
    -- "java",
    -- "kotlin",
    -- "c",
    -- "cpp",
    -- "cmake",
    -- "rust",
    -- "sql",
  },
}
